[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/Dockerfile.api-gateway"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
